server.port=${PORT:8080}
spring.thymeleaf.cache=true

# Gmail SMTP (mail s kojeg se salje)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=framarpodvodniradovi@gmail.com

#Ne upisuj pasword direktno ovdje za produkciju
#Lokalno moze, ali bolje je preko enviroment varijable:
spring.mail.password=#${GMAIL_APP_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

#Sluzbeni mail primatelj
framar.contact.to=framarpodvodniradovi@gmail.com

server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never
server.error.whitelabel.enabled=false
