
# Gmail SMTP (mail s kojeg se salje)
spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}

spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}

brevo.api.key=${BREVO_API_KEY}
brevo.sender=${BREVO_SENDER}
framar.contact.to=${FRAMAR_CONTACT_TO}


